FROM rust:1.79

WORKDIR /root

RUN apt -y update && apt -y install curl bzip2

RUN sh -c "$(curl -sSfL https://release.solana.com/v1.17.13/install)"

ENV PATH="/root/.local/share/solana/install/active_release/bin:${PATH}"

RUN solana-keygen new --no-bip39-passphrase

COPY .docker/devnet-accounts/ /root/accounts/

ENTRYPOINT ["solana-test-validator", "--bpf-program", "3fystoi7pB1cnDEbRRpSjFJA4fG3W2vQQZ21jSrBc11B", "/root/accounts/program1_11B.so", "--account-dir", "/root/accounts", "--reset"]
